Example: firebase deploy --token "$FIREBASE_TOKEN"
name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ repoToken: ${{ secrets.GITHUB_TOKEN }}
          # Usunąłem problematyczne linie stąd
          projectId: dziennik-elewatora
          channelId: live
 }}
               
        env:
                   FIREBASE_TOKEN: ${{ 09-el4p1O6XSsCgYIARAAGAkSNgF-L9IrQK5ILgW30pTNuBLu7XWmLW9wpFzokooSO9tydVFDk40yxc0-73LRbvRLGtR9DSOZfg
 }}